name: dart_lsp_collect_global_report
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  vm_service: ^14.3.1
  collection: ^1.19.1
  args: ^2.6.0
  # path: ^1.8.0

executables:
  dart_lsp_collect_global_report:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
